### ISSUE TITLE
Android App crashes on startup

### ISSUE THREAD

**Issue by joeredfearn** [Microsoft/AppCenter-SDK-Unity-Extension#32] opened 2019-05-10 13:38 UTC
I have recently installed the App Center SDK via the Unity Editor Extension. I followed the readme and added the secrets for each of my platforms however my Android build now crashes on startup with the 'has stopped responding' error.

After completely uninstalling the SDK the app worked absolutely fine again. Is there anyway I can retrieve some sort of crash log to help you help me work this out?

I am using the latest 2019 version of Unity.

Thanks for your time.

**Comment by maestersid** [comment] 2019-05-10 16:53
Hey! We are looking into this, looks like there are some compatibility issues with 2019, this is under investigation right now.

**Comment by annakocheshkova** [comment] 2019-05-12 14:03
@joeredfearn thank you for reporting this. Could you please send us the logs, just run in the terminal: `adb -d logcat AppCenter:V *:S`

**Comment by joeredfearn** [comment] 2019-05-13 09:55
sure thing I will get it to you sometime today

**Comment by joeredfearn** [comment] 2019-05-13 16:26
I hope this is what you are after. If not let me know and I can try again! I ran the command you mentioned above and then opened the app.

```
--------- beginning of /dev/log/main
--------- beginning of /dev/log/system
I/AppCenter(29624): App Center SDK configured successfully.
I/AppCenter(29624): Changed maximum database size to 10485760 bytes.
I/AppCenter(29624): Analytics service started from application.
I/AppCenter(29624): Distribute service started from application.
E/AppCenter(29624): Timeout waiting for looper tasks to complete.
```

**Comment by joeredfearn** [comment] 2019-05-15 10:51
Can I get a rough idea of when this issue is going to be fixed? Ideally we want to use App Center next week to distribute an Alpha build to a client.

I appreciate the work you are doing!

Thanks

**Comment by annakocheshkova** [comment] 2019-05-15 10:56
Hey @joeredfearn sorry for the long response! Could you remove the filter by AppCenter from the command and capture the full set of logs? Timeout happens on some uncaught Unity exception.

Also, does this happen only on Unity 2019 or it is not specific?

**Comment by joeredfearn** [comment] 2019-05-15 10:57
Sure I can do that for you, however I wouldn't be able to say if its just 2019 or not.

**Comment by joeredfearn** [comment] 2019-05-15 11:07
I had a look through the log and found the crash, I figured this is the specific bit you need - if you still need the full log then just let me know.

```
E/AppCenter(18374): Timeout waiting for looper tasks to complete.
E/AndroidRuntime(18374): FATAL EXCEPTION: AppCenter.Looper
E/AndroidRuntime(18374): Process: com.playerthree.smartspeed, PID: 18374
E/AndroidRuntime(18374): java.lang.Error: FATAL EXCEPTION [AppCenter.Looper]
E/AndroidRuntime(18374): Unity version     : 2019.1.0f2
E/AndroidRuntime(18374): Device model      : Pegatron Hudl 2
E/AndroidRuntime(18374): Device fingerprint: Hudl/HTF8A4XX/HTF8A4:4.4.2/KOT49H/rel.android-build.20150106.154003:user/release-keys
E/AndroidRuntime(18374):
E/AndroidRuntime(18374): Caused by: java.lang.NoClassDefFoundError: com.google.firebase.iid.FirebaseInstanceId
E/AndroidRuntime(18374):        at com.microsoft.appcenter.push.FirebaseUtils.getFirebaseInstanceId(FirebaseUtils.java:84)
E/AndroidRuntime(18374):        at com.microsoft.appcenter.push.FirebaseUtils.isFirebaseAvailable(FirebaseUtils.java:52)
E/AndroidRuntime(18374):        at com.microsoft.appcenter.push.Push.registerPushToken(Push.java:489)
E/AndroidRuntime(18374):        at com.microsoft.appcenter.push.Push.applyEnabledState(Push.java:299)
E/AndroidRuntime(18374):        at com.microsoft.appcenter.AbstractAppCenterService.onStarted(AbstractAppCenterService.java:206)
E/AndroidRuntime(18374):        at com.microsoft.appcenter.push.Push.onStarted(Push.java:352)
E/AndroidRuntime(18374):        at com.microsoft.appcenter.AppCenter.finishStartServices(AppCenter.java:922)
E/AndroidRuntime(18374):        at com.microsoft.appcenter.AppCenter.access$700(AppCenter.java:58)
E/AndroidRuntime(18374):        at com.microsoft.appcenter.AppCenter$8.run(AppCenter.java:844)
E/AndroidRuntime(18374):        at android.os.Handler.handleCallback(Handler.java:733)
E/AndroidRuntime(18374):        at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime(18374):        at android.os.Looper.loop(Looper.java:149)
E/AndroidRuntime(18374):        at android.os.HandlerThread.run(HandlerThread.java:61)
W/ActivityManager(  522):   Force finishing activity com.playerthree.smartspeed/com.unity3d.player.UnityPlayerActivity
I/WindowManager(  522): Screenshot max retries 4 of Token{225cd988 ActivityRecord{22515988 u0 com.playerthree.smartspeed/com.unity3d.player.UnityPlayerActivity t84 f}} appWin=Window{228af850 u0 Starting com.playerthree.smartspeed} drawState=4
W/WindowManager(  522): Screenshot failure taking screenshot for (1920x1200) to layer 21010
I/WifiHW  (  522): CMD: IFNAME=wlan0 SIGNAL_POLL
D/wpa_supplicant(  589): RX ctrl_iface - hexdump(len=11): 53 49 47 4e 41 4c 5f 50 4f 4c 4c
D/wpa_supplicant(  589): wlan0: Control interface command 'SIGNAL_POLL'
D/wpa_supplicant(  589): nl80211: survey data missing!
I/wpa_supplicant(  589): nl80211: send_and_recv->nl_recvmsgs failed: 20
```

**Comment by annakocheshkova** [comment] 2019-05-15 11:16
@joeredfearn it is enough. When you installed packages from the Extension, did you install Push package?
Would you mind sending me 2 screenshots:
1. A screenshot of your App Center configuration, like this (you can blur sensitive information): 
![image](https://user-images.githubusercontent.com/34677812/57771563-b837d580-771b-11e9-8875-08ce89ccbb91.png)

2. A screenshot of Assets folder, like this:
![image](https://user-images.githubusercontent.com/34677812/57771672-0d73e700-771c-11e9-8767-c828fea5902f.png)

I want to see the content of `AppCenter/Plugins/Android` and `Plugins/Android/res`

**Comment by joeredfearn** [comment] 2019-05-15 11:30
I installed the full SDK, the side panel claims that Push SDK 2.0.0 is installed!

![image1](https://user-images.githubusercontent.com/13364719/57772372-2d4fde80-770d-11e9-89d6-d37da1b55d53.jpg)
![image2](https://user-images.githubusercontent.com/13364719/57772375-2fb23880-770d-11e9-83ed-8c286955d5ee.jpg)
![image3](https://user-images.githubusercontent.com/13364719/57772385-317bfc00-770d-11e9-9b5b-59a92a26722f.jpg)

Let me know if that is not enough.

**Comment by annakocheshkova** [comment] 2019-05-15 11:50
Thanks @joeredfearn. Could you please check if there's a `PlayServicesResolver` folder inside Assets?

**Comment by joeredfearn** [comment] 2019-05-15 11:52
Yes there is.

**Comment by annakocheshkova** [comment] 2019-05-15 12:01
Interesting. Ok, I just reproduced your crash and it appears to be Unity 2019 specific. 

Could you please confirm if you intend to use Push module? 
The thing is, we use a certain set of build scripts to make Push module work and apparently they got broken with Unity 2019 release. 
If you are not planning to use Pushes, just un-check the "Use Push" checkbox in App Center settings. If you want to use the module, I can guide you through manual setup process.

**Comment by annakocheshkova** [comment] 2019-05-15 12:54
Btw @joeredfearn could please also confirm that there are no firebase aars inside `Plugins\Android` folder?

**Comment by joeredfearn** [comment] 2019-05-15 13:03
We wont be needing the Push module so I will disable it for the time being.

**Comment by joeredfearn** [comment] 2019-05-15 13:04
Yes i can confirm there is no firebase aars in that folder!

**Comment by annakocheshkova** [comment] 2019-05-15 13:26
@joeredfearn ok, let me know if it works now. 
Aside from that, could you send me the output from Unity console during the build (at the time when the app was broken)? It seemed to me that I reproduced the issue but now at second time it did not reproduce. I want to understand what caused it after all.

**Comment by joeredfearn** [comment] 2019-05-15 13:26
ok I will get that to you at some point today!

**Comment by joeredfearn** [comment] 2019-05-15 15:05
I hope this is what you are after.

[Editor.log](https://github.com/microsoft/AppCenter-SDK-Unity-Extension/files/3183164/Editor.log)

**Comment by joeredfearn** [comment] 2019-05-15 15:17
I can also confirm that disabling the Push setting has fixed the issue. Data is coming through now to the main portal.

Thank you for your help and I hope my information will prove helpful in fixing this issue once and for all!

**Comment by annakocheshkova** [comment] 2019-05-15 17:06
@joeredfearn glad it worked! I will close the issue, but I want to poke around a little bit to see why the scripts didn't run in your particular case (seems not Unity 2019 issue after all).

The log was not very informative, unfortunately. 
My next two guesses are: 
- Did you have a different version of `PlayServicesResolver` installed before App Center? 
- How many scenes are there? 

Could you also send me the screenshot of **PlayerSettings** and **BuildSettings** (the way you configured for build) when you have the time.

**Closed as completed by annakocheshkova** 2019-05-15 17:06 UTC
Labels: bug

**Comment by joeredfearn** [comment] 2019-05-16 09:33
1) As far as I am aware, no.
2) At the time it was crashing I had a single scene.

I will get some screenshots to you later if I have time.
